#!/bin/sh

command -v isabelle && exit 1
command -v Isabelle2020 && exit 1
[ -e ~/.local/share/Isabelle2020 ] && {
    echo "~/.local/share/Isabelle2020 exists"
    exit 1
}
[ -e ~/.local/bin/Isabelle2020 ] && {
    echo "~/.local/bin/Isabelle2020 exists"
    exit 1
}

mkdir -p ~/.local/share
mkdir -p ~/.local/bin

tmpdir=$(mktemp -d /tmp/isabelle-install.XXXXXXXXX)

curl https://isabelle.in.tum.de/dist/Isabelle2020_linux.tar.gz \
    -o "$tmpdir/isabelle.tar.gz"

tar -xzf "$tmpdir/isabelle.tar.gz" --directory "$HOME/.local/share"

cat > ~/.local/bin/Isabelle2020 <<EOL
#!/bin/sh

cd ~/.local/share/Isabelle2020
exec ./Isabelle2020
EOL
chmod u+x ~/.local/bin/Isabelle2020
echo "Created ~/.local/bin/Isabelle2020"

ln -s \
    "$HOME/.local/share/Isabelle2020/bin/isabelle" \
    "$HOME/.local/bin/isabelle"
echo "Created ~/.local/bin/isabelle"
