---
- name: Deploy dotfiles
  hosts: localhost
  vars:
      dotfiles: "{{ playbook_dir }}"
      home: "{{ ansible_facts['user_dir'] }}"
  tasks:
    - name: Update git submodules
      command: git submodule update --init
      register: git_submodules
      changed_when: git_submodules.stdout != ""
      tags: always
    - import_tasks: systemd/tasks.yaml
      tags: systemd
    - import_tasks: git/tasks.yaml
      tags: git
    - import_tasks: tmux/tasks.yaml
      tags: tmux
    - import_tasks: alacritty/tasks.yaml
      tags: alacritty
    - import_tasks: neovim/tasks.yaml
      tags: neovim
    - import_tasks: doom_emacs/tasks.yaml
      tags: emacs
    - import_tasks: fish/tasks.yaml
      tags: fish
    - import_tasks: restic/tasks.yaml
      tags: [ never, restic ]
    - import_tasks: other_tasks/applications.yaml
      tags: applications
    - import_tasks: other_tasks/gnome-utils.yaml
      tags: [ never, gnome-utils ]
