---
- name: Deploy dotfiles
  hosts: localhost
  vars:
      dotfiles: "{{ playbook_dir }}"
      home: "{{ ansible_facts['user_dir'] }}"
  tasks:
    - import_tasks: git/tasks.yaml
    - import_tasks: tmux/tasks.yaml
    - import_tasks: alacritty/tasks.yaml
    - tags: neovim
      import_tasks: neovim/tasks.yaml
    - tags: emacs
      import_tasks: doom_emacs/tasks.yaml
    - tags: fish
      import_tasks: fish/tasks.yaml
