#! /bin/sh
export TERMINAL='/home/mpardalos/.bin/colored_alacritty'
export SXHKD_SHELL='/usr/bin/sh'
export _JAVA_AWT_WM_NONREPARENTING=1 # For AWT to play nice
export STEAM_FRAME_FORCE_CLOSE=1 # Minimze steam to tray

# Programs that can/should start before bspwm config
~/.screenlayout/Desk.sh
wal -R 
! ( pgrep "picom"                ) && picom                &
! ( pgrep "sxhkd"                ) && sxhkd                &
! ( pgrep "dunst"                ) && dunst                &
! ( pgrep "lxqt-policykit-agent" ) && lxqt-policykit-agent &
! ( pgrep "blueman-applet"       ) && blueman-applet       &
! ( pgrep "redshift-gtk"         ) && redshift-gtk         &
! ( pgrep "nm-applet"            ) && nm-applet            &

xsetroot -cursor_name left_ptr # Set default cursor

bspc monitor primary -d 1 2 3 4 5

bspc config border_width               5
bspc config window_gap                 10

bspc config split_ratio                0.5
bspc config initial_polarity           second_child

bspc config borderless_monocle         false
bspc config gapless_monocle            false

bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

# bspc rule -a Alacritty state=floating rectangle=1000x600+460+240
bspc rule -a Emacs state=floating
bspc rule -a Zathura state=tiled
bspc rule -a gnuplot_qt state=floating
bspc rule -a sun-awt-X11-XFramePeer state=floating

~/.bin/start_polybar 
# ! ( pgrep "hexchat" ) && hexchat --minimize=2 &
[ -f ~/.fehbg ] && ~/.fehbg

# Focus on the middle desktop
bspc desktop --focus 3
