#! /bin/sh

export SXHKD_SHELL='/usr/bin/sh'
sxhkd &
compton -b
wal -R &
~/.config/dotfiles/lemonbar/bar.py &

# Keep lemonbar below
xdo above -t $(xdo id -n root) $(xdo id -n lemonbar)

bspc monitor primary -d    

bspc config border_width               5
bspc config window_gap                 10
bspc config top_padding                50

bspc config split_ratio                0.5
bspc config initial_polarity           second_child

bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config paddingless_monocle        true

bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc rule -a Firefox desktop=''
bspc rule -a Spotify desktop=''
bspc rule -a Alacritty state=floating

~/.bin/set_bspwm_colors
