# Shell variables
# Generated by 'wal'
wallpaper='/home/mpardalos/Pictures/Wallpapers/hex_moon.jpg'

# Special
background='#0f171b'
foreground='#98dfe1'
cursor='#98dfe1'

# Colors
color0='#0f171b'
color1='#CBB36E'
color2='#F0A46D'
color3='#276381'
color4='#655783'
color5='#AD6282'
color6='#1CB2FC'
color7='#98dfe1'
color8='#6a9c9d'
color9='#CBB36E'
color10='#F0A46D'
color11='#276381'
color12='#655783'
color13='#AD6282'
color14='#1CB2FC'
color15='#98dfe1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
