#!/bin/bash

####################################################
# I3block's blocklet which:
# - Displays time.
####################################################


t=$(date '+%H:%M | %d/%m/%Y')

echo "$t"
echo "$t"
echo
