# Shell variables
# Generated by 'wal'
wallpaper='{wallpaper}'

# Special
background='{background.strip}FF'
foreground='{foreground.strip}FF'
cursor='{cursor.strip}'

# Colors
color0='{color0.strip}FF'
color1='{color1.strip}FF'
color2='{color2.strip}FF'
color3='{color3.strip}FF'
color4='{color4.strip}FF'
color5='{color5.strip}FF'
color6='{color6.strip}FF'
color7='{color7.strip}FF'
color8='{color8.strip}FF'
color9='{color9.strip}FF'
color10='{color10.strip}FF'
color11='{color11.strip}FF'
color12='{color12.strip}FF'
color13='{color13.strip}FF'
color14='{color14.strip}FF'
color15='{color15.strip}FF'
