- name: Flatpak applications
  community.general.flatpak:
    name:
      - com.belmoussaoui.Authenticator
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - com.github.junrrein.PDFSlicer
      - com.spotify.Client
      - com.viber.Viber
      - org.telegram.desktop
