# vim: foldmethod=marker

# Silence verbose messages
set +m

# Print motd in a thread, this covers the time taken for the rest of the script with
# animated printing
~/.motd -t .001 &

# PATH
export PATH=$PATH:$HOME/.bin:/usr/local/bin:$HOME/.android/sdk/tools

# Execute lines with !! immediately
setopt no_hist_verify

export EDITOR=nvim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Aliases {{{
alias pacupdate="sudo pacman -Syu && echo '\nrepos \n--------------\naur \n' && pkgbuilder -Su"
alias dotfiles-update="git -C ~/.config/dotfiles pull"
alias g="git"
alias todo="nvim ~/Dropbox/todo/todo.txt"

function cd {
    builtin cd $1 && ls --color=auto
}

# open a directory in dolphin
function explore {
    dolphin $1 &>/dev/null &
}

function gnvim {
    konsole --profile neovim -e nvim $1 &>/dev/null &
}

function wc-tex {
    detex $1 | wc | awk '{print $2}'
}
# }}}

# Prompt {{{
autoload -U promptinit; promptinit
prompt pure
# }}}

wait

# Re-enable job messages
set -m
