#!/bin/sh

DEPENDS="curl nvim"

module_install() {
    ln -snf $1/neovim/ ~/.config/nvim

    curl --silent -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    nvim +PlugInstall +qa!
}

