#!/bin/sh
DOTS="$1"
DEPENDS="fish exa curl direnv"
OPTDEPENDS="gh"

module_install() {
    ln -sf "$1/fish" ~/.config/fish

    if fish -c "! type omf >/dev/null 2>&1 "; then
        echo
        echo "==> Downloading omf installer"
	curl --silent https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install -o /tmp/fish-install-omf

        echo
        echo "==> Running omf installer"
        chmod u+x /tmp/fish-install-omf
        /tmp/fish-install-omf --noninteractive
    fi

    echo "==> Setting omf theme"
    fish -c "omf install agnoster"
    fish -c "omf theme agnoster"

    command -v gh >/dev/null 2>&1 && {
        gh completion -s fish > ~/.config/fish/completions/gh.fish
    }
}
